xsd2go_type = {
    "ENTITIES": "string",
    "ENTITY": "string",
    "ID": "string",
    "IDREF": "string",
    "IDREFS": "string",
    "Name": "string",
    "NCName": "string",
    "NMTOKEN": "string",
    "NMTOKENS": "string",
    "normalizedString": "string",
    "QName": "string",
    "string": "string",
    "token": "string",

    "date": "string",
    "dateTime": "string",
    "duration": "string",
    "gDay": "string",
    "gMonth": "string",
    "gMonthDay": "string",
    "gYear": "string",
    "gYearMonth": "string",
    "time": "string",

    "byte": "int",
    "decimal": "float32",
    "int": "int",
    "integer": "int",
    "long": "int",
    "negativeInteger": "int",
    "nonNegativeInteger": "int",
    "nonPositiveInteger": "int",
    "positiveInteger": "int",
    "short": "int",
    "unsignedLong": "int",
    "unsignedInt": "int",
    "unsignedShort": "int",
    "unsignedByte": "int",

    "boolean": "bool",
    "base64Binary": "string",
    "hexBinary": "string",
    "anyURI": "string",
    "double": "float32",
    "float": "float32",

    "language": "string",
}